=== 13482477/spring-cloud-platform/spring-cloud-iproduct-webapp/src/main/resources/json/quoteRequestSchema.json
{
	"$schema":"http://json-schema.org/draft-04/schema",
	"type": "object",
	"properties": {
		"step": {
			"type": "string"
		},
	
		"productCode": {
			"type": "string"
		},
		
		"planCode": {
			"type": "string"
		},
		
		"effectiveDate": {
			"type": "string"
		},
		
		"mult": {
			"type": "string"
		},
		
		"insured": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					
					"idType": {
						"type": "string"
					},
					
					"idNo": {
						"type": "string"
					},
					
					"sex": {
						"type": "string"
					},
					
					"birthday": {
						"type": "string"
					},
					
					"nativePlace": {
						"type": "string"
					},
					
					"idValid": {
						"type": "string"
					},
					
					"relationToAppnt": {
						"type": "string"
					},
					
					"relationToMainInsured": {
						"type": "string"
					},
					
					"occupationCode": {
						"type": "string"
					},
					
					"major": {
						"type": "string"
					}
				}
			}
		},
		
		"plan": {
			"type": "array",
			"items": {
				"type":"object",
				"properties": {
					"code": {
						"type": "string"
					},
					
					"mult": {
						"type": "string"
					}
				}
			}			
		},
		
		"risks": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"riskCode": {
						"type": "string"
					},
					
					"amnt": {
						"type": "string"
					},
					
					"prem": {
						"type": "string"
					},
					
					"insuYear": {
						"type": "string"
					},
					
					"insuYearFlag": {
						"type": "string"
					},
					
					"insuranceType": {
						"type": "string"
					},
					
					"loanMonths": {
						"type": "string"
					},
					
					"loanMoney": {
						"type": "string"
					},
					
					"loanContNum": {
						"type": "string"
					},
					
					"borrowerLenderType": {
						"type": "string"
					},
					
					"loanType": {
						"type": "string"
					},
					
					"freeFlag": {
						"type": "string"
					},
					
					"loanYears": {
						"type": "string"
					},
					
					"floatRate": {
						"type": "string"
					},
					
					"loanDate": {
						"type": "string"
					},
					
					"rnewFlag": {
						"type": "string"
					},
					
					"payIntv": {
						"type": "string"
					},
					
					"payEndYear": {
						"type": "string"
					},
					
					"payEndYearFlag": {
						"type": "string"
					},
					
					"autoPayFlag": {
						"type": "string"
					},
					
					"bonusGetMode": {
						"type": "string"
					},
					
					"mult": {
						"type": "string"
					},
					
					"liveGetMode": {
						"type": "string"
					},
					
					"liveGetIntv": {
						"type": "string"
					},
					
					"liveGetYear": {
						"type": "string"
					},
					
					"liveGetYearFlag": {
						"type": "string"
					},
					
					"getEndPeriod": {
						"type": "string"
					},
					
					"getEndUnit": {
						"type": "string"
					},
					
					"duties": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"dutyCode": {
									"type": "string"
								},
								
								"Amnt": {
									"type": "string"
								},
								
								"Prem": {
									"type": "string"
								}
							}
						}
					},
					
					"plan": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"planCode": {
									"type": "string"
								},
								
								"mult": {
									"type": "string"
								},
								
								"amnt": {
									"type": "string"
								},
								
								"prem": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		}
		
	}
}

=== 13482477/spring-cloud-platform/spring-cloud-iproduct-webapp/src/main/resources/json/quoteRequest.json
{
	"step": "step1",
	"productCode": "BJXEDKYWX",
	"effectiveDate": "2017-06-19",
	"mult": "1",
	"insured": [
		{
			"name": "Adam",
			"idType": "identity",
			"idNo": "763465736483729384",
			"sex": "male",
			"birthday": "1999-09-01",
			"nativePlace": "Shanghai",
			"idValid": "Yes",
			"relationToAppnt": "self",
			"relationToMainInsured": "self",
			"occupationCode": "3306",
			"major": "ATEJF12"
		}
	],
	"plan": [
		{
			"code": "2017FJDOAF",
			"mult": "1"
		}
	],
	"risks": [
		{
			"riskCode": "test123",
			"amnt": "10000",
			"prem": "300",
			"insuYear": "2017",
			"insuYearFlag": "Yes",
			"insuranceType": "Workers' accident compensation insurance",
			"loadMonths": "24",
			"loadMoney": "10000",
			"loadContNum": "JREIOW1342",
			"borrowerLenderType": "borrower",
			"loadType": "Car",
			"freeFlag": "Yes",
			"loadYears": "2",
			"floatRate": "0.21",
			"loadDate": "2017-02-02",
			"rnewFlag": "No",
			"payIntv": "Monthly",
			"payEndYear": "2018",
			"payEndYearFlag": "No",
			"autoPayFlag": "No",
			"bonusGetMode": "Annually",
			"mult": "1",
			"liveGetMode": "EveryYear",
			"liveGetYear": "2018",
			"liveGetYearFlag": "No",
			"getEndPeriod": "2018",
			"getEndUnit": "",
			"duties":[
				{
					"dutyCode": "A123",
					"Amnt": "1000",
					"Prem": "10000"
				}
			],
			"plan": [
				{
					"planCode": "2017FJDOAF",
					"mult": "1",
					"amnt": "1000",
					"prem": "10000"
				}
			]
		}
	]
}
