=== 13482477/spring-cloud-platform/spring-cloud-uaa/src/main/resources/resource-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT resource (resource*)>
<!ATTLIST resource type (MENU|RESOURCE|SYSTEM|ROOT) #REQUIRED>
<!ATTLIST resource name ID #REQUIRED>
<!ATTLIST resource code CDATA #REQUIRED>
<!ATTLIST resource url CDATA>
<!ATTLIST resource description CDATA #IMPLIED>
<!ATTLIST resource httpMethod (GET|HEAD|POST|PUT|PATCH|DELETE|OPTIONS|TRACE) #IMPLIED>

=== 13482477/spring-cloud-platform/spring-cloud-uaa/src/main/resources/resource2.xml
<?xml version="1.0" standalone="no"?>    
<!DOCTYPE resource SYSTEM "resource-config.dtd" >
<resource code="SPRING_PLANTFORM" name="新保云" type="MENU">
	<resource code="SPRING_UAA" name="用户中心" type="SYSTEM">
		<resource 
				name="权限查询(角色ID)"
				type="RESOURCE" 
				code="UAA_AUTHORITIES_LOAD_BY_ROLE_ID" 
				url="/uaa/api/v1/authorities/resource/{resourceId}" 
				httpMethod="GET" 
				/>
		<resource 
				name="资源新增" 
				type="RESOURCE" 
				code="UAA_RESOURCE_CREATE" 
				url="/uaa/api/v1/resource" 
				httpMethod="POST"
				/>
		<resource 
				name="资源明细查询" 
				type="RESOURCE" 
				code="UAA_RESOURCE_DETAIL_LOAD" 
				url="/uaa/api/v1/resource/{id}" 
				httpMethod="GET" 
				/>
		<resource 
				name="资源删除" 
				type="RESOURCE" 
				code="UAA_RESOURCE_DELETE" 
				url="/uaa/api/v1/resource/{resourceId}" 
				httpMethod="DELETE" 
				/>
		<resource 
				name="资源修改" 
				type="RESOURCE" 
				code="UAA_RESOURCE_UPDATE" 
				url="/uaa/api/v1/resource/{resourceId}" 
				httpMethod="PUT" 
				/>
		<resource name="资源树查询(角色ID)" 
				type="RESOURCE" 
				code="UAA_RESOURCE_LOAD_BY_ROLE_ID" 
				url="/uaa/api/v1/resourceTree/{roleId}" 
				httpMethod="GET" 
				/>
		<resource name="资源查询(父节点)" 
				type="RESOURCE" 
				code="UAA_LOAD_CHILDREN_RESOURCES" 
				url="/uaa/api/v1/resources/parent/{parentId}" 
				httpMethod="GET" 
				/>
		<resource 
				name="资源和权限获查询(所有)" 
				type="RESOURCE" 
				code="UAA_LOAD_ALL_RESOURCE_AND_PERMISSION" 
				url="/uaa/api/v1/resourcesAndPermission" 
				httpMethod="GET" 
				/>
		<resource 
				name="角色创建" 
				type="RESOURCE" 
				code="UAA_CREATE_ROLE" 
				url="/uaa/api/v1/role" 
				httpMethod="POST" 
				/>
		<resource 
				name="角色修改" 
				type="RESOURCE" 
				code="UAA_UPDATE_ROLE" 
				url="/uaa/api/v1/role" 
				httpMethod="PUT" 
				/>
		<resource 
				name="角色授权" 
				type="RESOURCE" 
				code="UAA_ROLE_GRANT" 
				url="/uaa/api/v1/role/grant/{roleId}" 
				httpMethod="POST" />
		<resource 
				name="查询角色明细数据" 
				type="RESOURCE" 
				code="UAA_LOAD_ROLE_DEAIL" 
				url="/uaa/api/v1/role/{id}" 
				httpMethod="GET" 
				/>
		<resource 
				name="角色列表查询" 
				type="RESOURCE" 
				code="UAA_FIND_ROLES" 
				url="/uaa/api/v1/roles" 
				httpMethod="GET" 
				/>
		<resource 
				name="用户明细数据查询(用户ID)" 
				type="RESOURCE" 
				code="UAA_LOAD_USER_DETAIL" 
				url="/uaa/api/v1/roles/user/{userId}" 
				httpMethod="GET" 
				/>
		<resource 
				name="用户创建" 
				type="RESOURCE" 
				code="UAA_USER_CREATE" 
				url="/uaa/api/v1/user" 
				httpMethod="POST" 
				/>
		<resource 
				name="用户修改" 
				type="RESOURCE" 
				code="UAA_USER_UPDATE" 
				url="/uaa/api/v1/user" 
				httpMethod="PUT" 
				/>
		<resource 
				name="用户查询(用户名)" 
				type="RESOURCE" 
				code="UAA_USER_LOAD_BY_USER_NAME" 
				url="/uaa/api/v1/user/loadUserByUserName/{username}" 
				httpMethod="GET" 
				/>
	</resource>
</resource>
